# Utiliser une image Python de base
FROM python:3.12.3

# Définir le répertoire de travail à /app
WORKDIR /app

# Copier le fichier requirements.txt dans le répertoire de travail
COPY requirements.txt .

# Installer les dépendances nécessaires
RUN pip install --no-cache-dir -r requirements.txt

# Copier le reste de votre code source dans le répertoire de travail
COPY . .

# Exposer le port sur lequel votre application s'exécute (si nécessaire)
EXPOSE 8000

# Définir la commande pour exécuter votre application
CMD ["python", "main.py"]
